# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    AppBundle.db.table_prefix: f_

services:
#    service_name:
#        class: AcmeBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    disco.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, [@disco.logger_handler]]

    disco.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/disco.log, 200] # 200 is INFO

    appbundle.twig.classname:
        class: AppBundle\Twig\ClassTwigExtension
        tags:
            - { name: twig.extension }


    #added on 14/05/2015 in order to remove the 'f_' prefix to the generated entities by Doctrine
    #appbundle.tblprefix_subscriber:
        #class: AppBundle\Subscriber\TablePrefixSubscriber
        #arguments: [%AppBundle.db.table_prefix%]
        #tags:
        #    - { name: doctrine.event_subscriber }
